# Generated by Django 5.0.7 on 2025-12-02 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eegfile',
            name='file',
            field=models.FileField(upload_to='eeg_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['edf', 'csv', 'txt'])], verbose_name='Файл'),
        ),
    ]
