# Generated by Django 5.0.7 on 2026-01-19 22:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0002_alter_eegfile_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="EEGAnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата расчёта"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=150, verbose_name="Модель/алгоритм"),
                ),
                (
                    "emotion_label",
                    models.CharField(
                        choices=[
                            ("neutral", "Нейтральное состояние"),
                            ("calm", "Спокойствие"),
                            ("joy", "Радость"),
                            ("sadness", "Печаль"),
                            ("stress", "Стресс"),
                            ("fear", "Страх"),
                            ("anger", "Гнев"),
                            ("fatigue", "Утомление"),
                        ],
                        max_length=30,
                        verbose_name="Класс эмоции",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        help_text="Оценка уверенности классификатора (0-1).",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="Достоверность, 0-1",
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Метрики/признаки"
                    ),
                ),
                (
                    "visualization",
                    models.FileField(
                        blank=True,
                        upload_to="eeg_visuals/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg", "svg", "pdf"]
                            )
                        ],
                        verbose_name="Визуализация",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Комментарий аналитика"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_results",
                        to="records.eegsession",
                        verbose_name="Сеанс ЭЭГ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат анализа",
                "verbose_name_plural": "Результаты анализа",
                "ordering": ["-created_at"],
            },
        ),
    ]
